name: LeatherandLock
favicon: null
layout_spectrum: 1
typography_spectrum: 0.73251
title: 'Leather & Lock'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#080202'
    - '#33160e'
    - '#4b3736'
    - '#60524f'
    - '#89817e'
  brandStrength: 0.625
  lightness: 0.375
  saturation: 0.5599230085499585
  rhythmicContrast: 0.75
purpose: []
