name: LeatherandLock
favicon: null
layout_spectrum: 0.7373450216837227
typography_spectrum: 0.40756384190171957
title: 'Leather & Lock'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.5906833941116929
  lightness: 0.6637898997869343
  saturation: 0.5599230085499585
  rhythmicContrast: 0.6263458458706737
purpose: []
